### ISSUE TITLE
fence_apc_snmp.py error on python3

### ISSUE THREAD

**Issue by feldsam** [ClusterLabs/fence-agents#132]
Hello, when I use fence_apc_snmp.py on fedora 26 with python 3 I get this error

        Traceback (most recent call last):
          File "./fence_apc_snmp.py", line 224, in <module>
            main()
          File "./fence_apc_snmp.py", line 220, in main
            result = fence_action(FencingSnmp(options), options, set_power_status, get_power_status, get_outlets_status)
          File "/usr/share/fence/fencing.py", line 780, in fence_action
            outlets = get_outlet_list(connection, options)
          File "./fence_apc_snmp.py", line 172, in get_outlets_status
            apc_set_device(conn)
          File "./fence_apc_snmp.py", line 114, in apc_set_device
            apc_type = conn.walk(OID_SYS_OBJECT_ID)
          File "/usr/share/fence/fencing_snmp.py", line 132, in walk
            output = self.run_command(cmd, additional_timemout).splitlines()
          File "/usr/share/fence/fencing_snmp.py", line 100, in run_command
            if (res_code != 0) or (re.search("^Error ", res_output, re.MULTILINE) != None):
          File "/usr/lib64/python3.6/re.py", line 182, in search
            return _compile(pattern, flags).search(string)
        TypeError: cannot use a string pattern on a bytes-like object

I also try latest version from this repo with sam error

**Comment by vvidic** [comment]
This seems to be fixed now?

**Comment by oalbrigt** [comment]
This should be fixed now.

@feldsam re-open this issue if it's still an issue.
