### ISSUE TITLE
fence_vmware_rest will emit a noisy log if fencing fails

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#301]
Hi All,

We are testing fence_vmware_reset.

If the ESXi host on which the guest to be fenced starts is powered down and fencing fails several times, the following stack trace logs are output in large quantities.
This is a very noisy log.

```
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [ Traceback (most recent call last): ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/sbin/fence_vmware_rest", line 110, in send_command ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     conn.perform() ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [ pycurl.error: (28, 'Operation timed out after 5001 milliseconds with 0 bytes received') ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [  ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [ During handling of the above exception, another exception occurred: ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [  ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [ Traceback (most recent call last): ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/sbin/fence_vmware_rest", line 183, in <module> ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     main() ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/sbin/fence_vmware_rest", line 178, in main ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     result = fence_action(conn, options, set_power_status, get_power_status, get_list) ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/share/fence/fencing.py", line 899, in fence_action ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     if set_multi_power_fn(connection, options, set_power_fn, get_power_fn, sync_set_power_fn): ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/share/fence/fencing.py", line 808, in set_multi_power_fn ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     return async_set_multi_power_fn(connection, options, set_power_fn, get_power_fn, retry_attempts) ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/share/fence/fencing.py", line 771, in async_set_multi_power_fn ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     set_power_fn(connection, options) ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/sbin/fence_vmware_rest", line 31, in set_power_status ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     send_command(conn, "vcenter/vm/{}/power/{}".format(options["id"], action), "POST") ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [   File "/usr/sbin/fence_vmware_rest", line 112, in send_command ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [     raise Exception(e[1]) ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (log_action)        warning: fence_vmware_rest[17472] stderr: [ TypeError: 'error' object does not support indexing ]
Oct 08 15:24:47 rh80-02 pacemaker-fenced    [16968] (internal_stonith_action_execute
```

The cause seems to be insufficient exception for send_command.
Temporarily, the log decreased when the following corrections were made.

```
@@ -11,7 +11,10 @@ from fencing import fail, run_delay, EC_
 state = {"POWERED_ON": "on", 'POWERED_OFF': "off"}
 
 def get_power_status(conn, options):
-       res = send_command(conn, "vcenter/vm?filter.names={}".format(options["--plug"]))["value"]
+       try:
+               res = send_command(conn, "vcenter/vm?filter.names={}".format(options["--plug"]))["value"]
+       except Exception as e:
+               logging.debug("Failed: {}".format(e))
 
        if len(res) == 0:
                fail(EC_STATUS)
@@ -28,12 +31,18 @@ def set_power_status(conn, options):
                "off" : "stop"
        }[options["--action"]]
 
-       send_command(conn, "vcenter/vm/{}/power/{}".format(options["id"], action), "POST")
+       try:
+               send_command(conn, "vcenter/vm/{}/power/{}".format(options["id"], action), "POST")
+       except Exception as e:
+               logging.debug("Failed: {}".format(e))
 
 def get_list(conn, options):
        outlets = {}
 
-       res = send_command(conn, "vcenter/vm")
+       try:
+               res = send_command(conn, "vcenter/vm")
+       except Exception as e:
+               logging.debug("Failed: {}".format(e))
 
        for r in res["value"]:
                outlets[r["name"]] = ("", state[r["power_state"]])
@@ -87,7 +96,10 @@ def connect(opt):
        return conn
 
 def disconnect(conn):
-       send_command(conn, "com/vmware/cis/session", "DELETE")
+       try:
+               send_command(conn, "com/vmware/cis/session", "DELETE")
+       except Exception as e:
+               logging.debug("Failed: {}".format(e))
        conn.close()
 
 def send_command(conn, command, method="GET"):
```

We want you to catch the exception correctly and reduce the noisy log.

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
You might want to adjust the `shell_timeout` and `power_wait` values and see if that solves the issue for you.

I'll try to improve the logging based on your feedback.

**Comment by oalbrigt** [comment]
Here's a patch based on how it's done in fence_vmware_vcloud combined with your suggestion:
https://github.com/ClusterLabs/fence-agents/pull/302

**Comment by HideoYamauchi** [comment]
Hi oalbrigt,

Thank you for the response.
I will test your fix.

Many thanks
Hideo Yamauchi.
